import {initial,bootstrapEnv} from './report-r3-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { ReportLedger, validateReport, applyNativeCorrection } from '../functions/_shared/native-report.js';
import { nativeReportWebhook } from '../functions/_shared/native-report-webhook.js';
import { receiveNativeReport } from '../functions/_shared/native-report-receiver.js';
import { boundedJson } from '../functions/_shared/native-report-publisher.js';
import { correctionFiles } from '../scripts/banks/report-correction-files.mjs';
import { onRequestPost as feedbackPost } from '../functions/api/feedback.js';
import { finalizeRegisteredQuestions } from '../src/domain/question/registered-identity.js';
import { validateBankContent } from '../src/domain/question/bank-content.js';

const uid='11111111-1111-4111-8111-111111111111',qid='22222222-2222-4222-8222-222222222222';
async function fixture(){
  const questions=await finalizeRegisteredQuestions([qid,'33333333-3333-4333-8333-333333333333'].map(questionUid=>({bankUid:uid,questionUid,questionKey:`${uid}/${questionUid}`,question:'Same stem',choices:['A','B'],answer:0,provenance:[]})));
  const content={format:'qb-bank-content-v2',schemaVersion:1,bankUid:uid,metadata:{title:'Public test',visibility:'public',questionCount:2},questions};
  const verified=await validateBankContent(content);
  const source={bankUid:uid,revision:verified.contentDigest,visibility:'public',sourcePath:'content/test.registered.json',manifestPath:'content/manifest.json',registryPath:'content/registry.json'};
  const body={schema_version:2,operationId:crypto.randomUUID(),bankUid:uid,revision:verified.contentDigest,questionUid:qid,questionKey:`${uid}/${qid}`,questionRevision:questions[0].questionRevision,corrected:{question:'Same stem',choices:['A','B'],answer:1},note:''};
  return {content,source,body};
}
function ledger(){const db=new DatabaseSync(':memory:');return new ReportLedger({sql:{exec(query,...values){const statement=db.prepare(query);const rows=statement.columns().length ? statement.all(...values) : (statement.run(...values),[]);return {toArray:()=>rows};}}});}
test('exact UID corrects the second duplicate without first-stem matching; immutable old content',async()=>{const {content,source,body}=await fixture();body.questionUid=content.questions[1].questionUid;body.questionKey=content.questions[1].questionKey;const pending=validateReport(body,[source]);const result=await applyNativeCorrection(content,pending);assert.equal(result.content.questions[0].answer,0);assert.equal(result.content.questions[1].answer,1);assert.equal(content.questions[1].answer,0);assert.equal(result.content.questions[1].questionUid,body.questionUid);assert.notEqual(result.revision,source.revision);});
test('stale bank/question versions and private identities fail closed',async()=>{const {content,source,body}=await fixture();assert.throws(()=>validateReport(body,[{...source,visibility:'private'}]),/PUBLIC_SOURCE/);assert.throws(()=>validateReport({...body,revision:'0'.repeat(64)},[source]),/REVISION_CONFLICT/);await assert.rejects(applyNativeCorrection(content,{...body,questionRevision:'0'.repeat(64)}),/QUESTION_CONFLICT/);});
test('invalid answer indices, unknown edit fields, and ambiguous answers rejected',async()=>{const {source,body}=await fixture();for(const corrected of [{question:'x',choices:['a','b'],answer:9},{question:'x',path:'banks/evil'},{question:'x',choices:['a','b'],answer:0,answers:[1]}])assert.throws(()=>validateReport({...body,corrected},[source]),/CORRECTION_INVALID/);});
test('ledger identical retries, payload collision, and concurrent claim',async()=>{const {source,body}=await fixture(),store=ledger(),pending=validateReport(body,[source]);await Promise.all([store.receive(pending),store.receive(pending)]);assert.equal(store.get(body.operationId).state,'received');const claims=await Promise.all([store.transition(body.operationId,'received','delivering'),store.transition(body.operationId,'received','delivering')]);assert.equal(claims.filter(Boolean).length,1);await assert.rejects(store.receive({...pending,note:'changed'}),/OPERATION_CONFLICT/);await assert.rejects(store.transition(body.operationId,'delivering','published'),/TRANSITION_INVALID/);});
test('atomic correction packet preserves old content and patches same native registry',async()=>{const {content,source,body}=await fixture();const manifest={banks:[{slug:'test',bankUid:uid,revision:source.revision,contentFile:'test.registered.json'}]},registry={questions:content.questions.map(q=>({questionKey:q.questionKey,questionRevision:q.questionRevision}))};const result=await correctionFiles(content,manifest,registry,body,source);assert.equal(result.files.length,3);assert.notEqual(result.files[0].path,source.sourcePath);const next=JSON.parse(result.files[2].content);assert.notEqual(next.questions[0].questionRevision,registry.questions[0].questionRevision);assert.equal(next.questions[1].questionRevision,registry.questions[1].questionRevision);});
test('provider response bound is enforced while streaming',async()=>{await assert.rejects(boundedJson(new Response('x'.repeat(20)),10),/TOO_LARGE/);});
test('Telegram timeout retains saved operation and retry does not redeliver',async()=>{const {source,body}=await fixture(),store=ledger();store.releaseHead(initial);const env={REPORT_SOURCES_JSON:JSON.stringify([source]),REPORT_OPERATIONS:{getByName:()=>store},TELEGRAM_BOT_TOKEN:'fake',TELEGRAM_APPROVER_IDS:'456',TELEGRAM_CHAT_ID:'fake'};let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw Error('timeout');};try{const first=await receiveNativeReport(body,env),second=await receiveNativeReport(body,env);assert.equal(first.stored,true);assert.equal(first.delivered,false);assert.equal(second.state,'delivery_unknown');assert.equal(calls,1);}finally{globalThis.fetch=original;}});
test('missing webhook secret denies without contacting any provider',async()=>{const response=await nativeReportWebhook({request:new Request('https://test',{method:'POST',body:'{}'}),env:{}});assert.equal(response.status,403);});
test('question correction preserves Turnstile gate before ledger/provider',async()=>{const {body}=await fixture();const response=await feedbackPost({request:new Request('https://test/api/feedback',{method:'POST',body:JSON.stringify({...body,kind:'question_edit'})}),env:{TELEGRAM_BOT_TOKEN:'fake',TELEGRAM_APPROVER_IDS:'456',TELEGRAM_CHAT_ID:'fake',TURNSTILE_SECRET_KEY:'fake'}});assert.equal(response.status,400);assert.equal((await response.json()).error,'captcha_missing');});
test('schema2 general feedback stays a message without creating approval ledger',async()=>{const saved=[],env={TELEGRAM_BOT_TOKEN:'fake',TELEGRAM_APPROVER_IDS:'456',TELEGRAM_CHAT_ID:'fake',EDITS:{put:async(key,value)=>saved.push([key,value])}};const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({ok:true});try{const response=await feedbackPost({request:new Request('https://test/api/feedback',{method:'POST',body:JSON.stringify({schema_version:2,kind:'general_feedback',message:'Plain suggestion'})}),env});assert.equal(response.status,200);assert.equal(saved.length,1);assert.match(saved[0][0],/^fb:/);}finally{globalThis.fetch=original;}});
