import test from 'node:test';import assert from 'node:assert/strict';import {verifyReportOIDC,assertReportRunBinding} from '../functions/_shared/report-oidc.js';
const policy={audience:'https://question-bank-78u.pages.dev/api/report-control',workflowSha:'a'.repeat(40),workflowPaths:['shicheng0810/question-bank-source/.github/workflows/report-publication.yml@refs/heads/main']};
const claims={iss:'https://token.actions.githubusercontent.com',aud:policy.audience,repository:'shicheng0810/question-bank-source',repository_id:'1403515803',repository_owner_id:'74512891',ref:'refs/heads/main',environment:'report-production',event_name:'workflow_dispatch',sub:'repo:shicheng0810/question-bank-source:environment:report-production',workflow_sha:policy.workflowSha,sha:policy.workflowSha,workflow_ref:policy.workflowPaths[0],run_id:'123',run_attempt:'1',iat:1000,nbf:1000,exp:1300,jti:'synthetic-jti'};
const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk={...await crypto.subtle.exportKey('jwk',pair.publicKey),kid:'synthetic',alg:'RS256',use:'sig'};
const encode=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');async function signed(value,header={alg:'RS256',kid:'synthetic'}){const input=encode(header)+'.'+encode(value),signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(input));return input+'.'+Buffer.from(signature).toString('base64url');}
const options={now:1100,fetchKeys:async()=>({keys:[jwk]})};
test('actual WebCrypto signature and exact repository/workflow/environment/commit admits trusted job',async()=>{assert.equal((await verifyReportOIDC(await signed(claims),policy,options)).runId,'123');});
test('wrong owner/repo id, fork/PR/ref, audience, environment, workflow path/SHA/commit, expiry and algorithm denied',async()=>{for(const key of ['iss','aud','repository','repository_id','repository_owner_id','ref','environment','event_name','sub','workflow_sha','sha','workflow_ref'])await assert.rejects(verifyReportOIDC(await signed({...claims,[key]:'wrong'}),policy,options),/DENIED/);for(const change of [{exp:1000},{iat:1200},{nbf:1200},{exp:1800},{jti:''}])await assert.rejects(verifyReportOIDC(await signed({...claims,...change}),policy,options),/DENIED/);await assert.rejects(verifyReportOIDC(await signed(claims,{alg:'HS256',kid:'synthetic'}),policy,options),/DENIED/);});
test('tampered token, duplicate signing key and missing policy cannot authorize control',async()=>{const token=await signed(claims);await assert.rejects(verifyReportOIDC(token.slice(0,-8)+'badtoken',policy,options),/DENIED/);await assert.rejects(verifyReportOIDC(token,policy,{...options,fetchKeys:async()=>({keys:[jwk,jwk]})}),/DENIED/);await assert.rejects(verifyReportOIDC(token,null,options),/DENIED/);});

test('operation and workflow run/attempt replays cannot cross durable publication binding',()=>{const job={runId:'123',runAttempt:'1',workflowSha:'a'.repeat(40)},binding={...job,operationId:'synthetic-operation',fence:1};assertReportRunBinding(job,binding,'synthetic-operation',1);for(const change of [{runId:'124'},{runAttempt:'2'},{workflowSha:'b'.repeat(40)}])assert.throws(()=>assertReportRunBinding({...job,...change},binding,'synthetic-operation',1),/DENIED/);assert.throws(()=>assertReportRunBinding(job,binding,'other-operation',1),/DENIED/);});
