import {settings,projectConfig} from './report-r3-fixture.mjs';
import {createHash} from 'node:crypto';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createReadStream} from 'node:fs';import {createServer} from 'node:http';import path from 'node:path';import {buildReportRelease} from '../scripts/banks/report-cloudflare-adapter.mjs';import {verifyOnlineRelease} from '../scripts/banks/verify-report-online.mjs';import {reportDeploymentURL} from '../functions/_shared/report-deployment-url.js';
test('actual production build static bytes verify over local HTTP using validated provider URL, never UUID hostname',async()=>{
 const root=process.cwd(),manifest=JSON.parse(await readFile('production-inputs/registered-banks.json','utf8')),bank=manifest.banks[0],content=JSON.parse(await readFile(path.join('production-inputs',bank.contentFile),'utf8')),q=content.questions[0];
 const plan={operationId:crypto.randomUUID(),resultCommit:'a'.repeat(40),domain:'question-bank-78u.pages.dev',bankUid:bank.bankUid,revision:bank.revision,contentHash:bank.revision,questionKey:q.questionKey,questionRevision:q.questionRevision,staticRef:bank.staticRef};
 const rawPlan=structuredClone(plan);
 const release=await buildReportRelease({root,plan,settings,api:async()=>projectConfig}),deployment={deploymentId:'12345678-1234-4234-8234-123456789abc',shortId:'12345678',url:'https://12345678.question-bank-78u.pages.dev/',resultCommit:plan.resultCommit,workerVersionId:crypto.randomUUID()};plan.artifact=release.artifact;plan.controlJob={runId:'1',runAttempt:'1',workflowSha:'a'.repeat(40),fence:1};deployment.uploadReceipt={schema:3,operationId:plan.operationId,resultCommit:plan.resultCommit,artifactHash:release.artifact.sha256,target:plan.domain,...plan.controlJob,workerHash:release.artifact.worker.sha256,workerMetadataHash:release.artifact.worker.metadataHash,pagesBundleHash:release.artifact.pagesBundleHash,pagesContractHash:release.artifact.pagesContractHash,staticManifestHash:'f'.repeat(64),workerVersionId:deployment.workerVersionId,workerDeploymentId:crypto.randomUUID(),deploymentId:deployment.deploymentId,workerUploadResponseId:deployment.workerVersionId,pagesUploadResponseId:deployment.deploymentId};const again=await buildReportRelease({root,plan:rawPlan,settings,api:async()=>projectConfig});assert.deepEqual(again.artifact,release.artifact);const activePointers={workerVersionId:deployment.workerVersionId,workerDeploymentId:deployment.uploadReceipt.workerDeploymentId,workerPercentage:100,workerVersions:1,pagesDeploymentId:deployment.deploymentId,project:'question-bank',environment:'production',commit:plan.resultCommit,status:'success',pagesBundleHash:release.artifact.pagesBundleHash,workerHash:release.artifact.worker.sha256};assert.equal(reportDeploymentURL(deployment,plan.resultCommit),deployment.url);
 const parts=await new Response(await readFile(path.join(release.output,'_worker.bundle')),{headers:{'content-type':'multipart/form-data; boundary=qb-report-frozen-bundle-v3'}}).formData();assert.equal(Buffer.from(await parts.get('_worker.js').arrayBuffer()).equals(await readFile(path.join(release.output,'_worker.js'))),true);assert.equal(createHash('sha256').update(release.workerBytes).digest('hex'),release.artifact.worker.sha256);
 for(const patch of [{url:'https://evil.invalid/'},{url:'https://u:p@12345678.question-bank-78u.pages.dev/'},{url:deployment.url+'path'},{url:'https://'+deployment.deploymentId+'.question-bank-78u.pages.dev/'},{resultCommit:'b'.repeat(40)}])assert.throws(()=>reportDeploymentURL({...deployment,...patch},plan.resultCommit),/TARGET/);
 const server=createServer((req,res)=>{const url=new URL(req.url,'http://local');if(url.pathname.includes('..')){res.writeHead(400).end();return;}createReadStream(path.join(release.output,url.pathname)).on('error',()=>res.writeHead(404).end()).pipe(res);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port,requested=[];
 try{const proof=await verifyOnlineRelease({plan,deployment,releaseManifest:release.manifest.filter(r=>!['_worker.js','_routes.json','_worker.bundle','_headers','_redirects'].includes(r.path)),readLocal:p=>readFile(path.join(release.output,p)),fetchHTTP:async(u,opts)=>{const url=new URL(u);requested.push(url.origin);return fetch(new URL(url.pathname,origin),opts);},workerReadback:async()=>({versionId:deployment.workerVersionId,gatesVerified:true,registryVerified:true,activePointers})});assert.equal(proof.allPublishedBytesVerified,true);assert.deepEqual([...new Set(requested)],[new URL(deployment.url).origin,'https://question-bank-78u.pages.dev']);}finally{await new Promise(resolve=>server.close(resolve));}
});
