import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import vm from 'node:vm';
const source=readFileSync(new URL('../src/templates/question-bank-template.html',import.meta.url),'utf8');
function setup(){const dom=new JSDOM('<div id="qb-report" hidden><div id="qb-report-ctx"></div><div id="qb-edit-body"></div><textarea id="qb-report-msg"></textarea><input id="qb-report-hp"><button id="qb-report-send"></button><div id="qb-report-status"></div></div>',{url:'https://current.example/player.html?bank=public'});const document=dom.window.document,q={id:'q',bankUid:'bank',questionKey:'bank/question',questionRevision:'exact-q',question:'Original',choices:['A','B'],answer:0};const body={bankUid:'bank',metadata:{visibility:'public'},questions:[q]};const timers=[];const context={document,crypto,URL,location:dom.window.location,navigator:dom.window.navigator,window:dom.window,console,setTimeout:fn=>timers.push(fn),DATA_V2_SESSION_GENERATION:1,DATA_V2_BODIES:[{content:body}],DATA_V2_PUBLIC_READONLY:{entry:{bankUid:'bank',revision:'exact-bank'}},DATA_V2_MODULE:{validateBankContent:async()=>({contentDigest:'exact-bank'})},UI_FEATURES:{feedback:true},IS_PRIVATE_BANK:false,IS_SPECIAL:false,NATIVE_ONLY_MODE:true,FEEDBACK_CONFIG:{endpoint:'https://old.example/api/feedback'},STORAGE_NS:'public',uiLang:'en',getQ:()=>q,dataV2NeedsFullQuestion:()=>false,dataV2HydrateFullQuestion:async()=>{},T:key=>key,isMulti:()=>false,isFill:()=>false,isEssay:()=>false};vm.createContext(context);const feedback=source.slice(source.indexOf('let REPORT_CTX ='),source.indexOf('/* ================= 登录'));const report=source.slice(source.indexOf('var EDIT_ORIG=null'),source.indexOf('/* ---- 通用建议 ---- */'));vm.runInContext(feedback+'\n'+report,context);return {context,document,q,body,timers};}
function change(d){d.getElementById('qb-edit-stem').value='Corrected';}
test('actual form open/confirm/cancel preserves question and exact revision, current origin; duplicate click once',async()=>{const {context:c,document:d}=setup();let calls=0,resolve;c.fetch=async(url,options)=>{calls++;assert.equal(url,'https://current.example/api/feedback');const payload=JSON.parse(options.body);assert.equal(payload.revision,'exact-bank');assert.equal(payload.questionRevision,'exact-q');assert.equal(payload.page_url,undefined);return new Promise(r=>resolve=()=>r(Response.json({ok:true})));};await c.openReportModal('q',1);c.closeReportModal();assert.equal(calls,0);await c.openReportModal('q',1);change(d);const first=c.onReportSubmit();await new Promise(r=>setImmediate(r));await c.onReportSubmit();assert.equal(calls,1);resolve();await first;assert.equal(d.getElementById('qb-report-status').textContent,'fb_thanks');});
test('submit failure retains form and retry same operation; edit change new operation',async()=>{const {context:c,document:d}=setup();const ids=[];c.fetch=async(u,o)=>{ids.push(JSON.parse(o.body).operationId);return Response.json(ids.length===1?{ok:false,error:'FAIL'}:{ok:true});};await c.openReportModal('q',1);change(d);await c.onReportSubmit();assert.equal(d.getElementById('qb-report').hidden,false);assert.match(d.getElementById('qb-report-status').textContent,/FAIL/);await c.onReportSubmit();assert.equal(ids[0],ids[1]);d.getElementById('qb-edit-stem').value='Different';await c.onReportSubmit();assert.notEqual(ids[1],ids[2]);});
test('cancel/reopen and account generation changes ignore late reply and old auto-close timer',async()=>{const {context:c,document:d,timers}=setup();let resolve;c.fetch=()=>new Promise(r=>resolve=()=>r(Response.json({ok:true})));await c.openReportModal('q',1);change(d);const pending=c.onReportSubmit();await new Promise(r=>setImmediate(r));c.closeReportModal();await c.openReportModal('q',2);resolve();await pending;assert.equal(d.getElementById('qb-report-status').textContent,'');assert.equal(d.getElementById('qb-report-send').disabled,false);c.fetch=async()=>Response.json({ok:true});change(d);await c.onReportSubmit();await c.openReportModal('q',3);timers.forEach(fn=>fn());assert.equal(d.getElementById('qb-report').hidden,false);change(d);c.DATA_V2_SESSION_GENERATION++;await c.onReportSubmit();assert.equal(d.getElementById('qb-report').hidden,true);});
test('private body and special bank cannot open report; asynchronous hydration cannot resurrect cancelled dialog',async()=>{const {context:c,document:d,body}=setup();body.metadata.visibility='private';await c.openReportModal('q',1);assert.equal(d.getElementById('qb-report').hidden,true);body.metadata.visibility='public';c.IS_SPECIAL=true;await c.openReportModal('q',1);assert.equal(d.getElementById('qb-report').hidden,true);c.IS_SPECIAL=false;let done;c.dataV2NeedsFullQuestion=()=>true;c.dataV2HydrateFullQuestion=()=>new Promise(r=>done=r);const opening=c.openReportModal('q',1);c.closeReportModal();done();await opening;assert.equal(d.getElementById('qb-report').hidden,true);});
