import test from 'node:test';import assert from 'node:assert/strict';import {cp,mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {produceCorrection,parseReportExtension} from '../scripts/banks/apply-native-report-request.mjs';import {validateReportPR} from '../scripts/banks/validate-native-report-pr.mjs';import {importReportData} from '../scripts/banks/report-data-import.mjs';import {validateReport} from '../functions/_shared/native-report.js';import {publicCorrection} from '../functions/_shared/public-report-contract.js';
test('two exact approved correction commits validate and import from fresh trusted checkout, preserving prior immutable data only',async()=>{
 const root=await mkdtemp(path.join(process.cwd(),'r3-history-')),proposed=path.join(root,'proposed');
 async function copyData(destination){await mkdir(path.join(destination,'do-worker/src'),{recursive:true});for(const dir of ['production-inputs','content'])await cp(path.join(process.cwd(),dir),path.join(destination,dir),{recursive:true});for(const name of ['reviewed-report-public-registry.generated.js','account-public-registry.generated.js'])await cp(path.join(process.cwd(),'do-worker/src',name),path.join(destination,'do-worker/src',name));}
 await copyData(proposed);const git=(...args)=>execFileSync('git',args,{cwd:proposed,encoding:'utf8',env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}}).trim();git('init','--quiet');git('add','.');git('-c','user.name=Local Synthetic','-c','user.email=local@example.invalid','commit','--quiet','-m','synthetic reviewed baseline');let previousPath;
 for(let n=1;n<=2;n++){
  const base=git('rev-parse','HEAD'),sources=JSON.parse(git('show',base+':content/report-sources.json')),source=sources[0],content=JSON.parse(git('show',base+':'+source.sourcePath)),q=content.questions[0],operationId=crypto.randomUUID();
  const pending=validateReport({schema_version:2,operationId,bankUid:source.bankUid,revision:source.revision,questionUid:q.questionUid,questionKey:q.questionKey,questionRevision:q.questionRevision,corrected:{question:'Synthetic local continuity correction '+n},note:''},sources),request={format:'qb-native-report-request-v1',baseCommit:base,pending:publicCorrection(pending)};
  const packet=await produceCorrection(request,sources,async(commit,file)=>{const text=git('show',commit+':'+file);if(file.endsWith('reviewed-report-public-registry.generated.js'))return parseReportExtension(text);if(file.endsWith('account-public-registry.generated.js'))return JSON.parse(JSON.parse(text.match(/publicRegistryJson = ("(?:[^"\\]|\\.)*");/)[1]));return JSON.parse(text);});
  const requestPath='content/report-requests/'+operationId+'.json';await mkdir(path.dirname(path.join(proposed,requestPath)),{recursive:true});await writeFile(path.join(proposed,requestPath),JSON.stringify(request));for(const file of packet.files)await writeFile(path.join(proposed,file.path),file.content);git('add','.');git('-c','user.name=Local Synthetic','-c','user.email=local@example.invalid','commit','--quiet','-m','synthetic approved correction '+n);const expectedCommit=git('rev-parse','HEAD');
  const verified=await validateReportPR({root:proposed,base,head:expectedCommit,operationId,sourcesFile:'content/report-sources.json'}),trusted=path.join(root,'trusted-'+n);await copyData(trusted);await importReportData({trustedRoot:trusted,dataRoot:proposed,verified,requestPath,expectedCommit});
  assert.equal(JSON.parse(await readFile(path.join(trusted,'content/report-sources.json'),'utf8'))[0].revision,packet.revision);if(previousPath)assert.equal(await readFile(path.join(trusted,previousPath),'utf8'),git('show',base+':'+previousPath));previousPath=packet.files[0].path;
 }
});
