import {initial,bootstrapEnv} from './report-r3-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {ReportLedger,validateReport} from '../functions/_shared/native-report.js';import {approvalPacket,assertApprovalCallback,REPORT_SOURCE_BASE} from '../functions/_shared/report-approval.js';import {reportFixture} from './report-runtime/fixture.js';import {nativeReportWebhook} from '../functions/_shared/native-report-webhook.js';import {publicCorrection} from '../functions/_shared/public-report-contract.js';
function store(){const db=new DatabaseSync(':memory:');return {db,ledger:new ReportLedger({sql:{exec(q,...v){const stmt=db.prepare(q);const rows=stmt.columns().length?stmt.all(...v):(stmt.run(...v),[]);return {toArray:()=>rows}}}})};}
test('complete sizeable correction is visible; wrong message, nonce, chat, payload, expired/ancient callback reject; normal approval succeeds once',async()=>{
 const f=await reportFixture();f.body.corrected={question:'Q'.repeat(800),choices:['A'.repeat(450),'B'.repeat(450)],answer:1};const pending=validateReport(f.body,[f.source]),packet=await approvalPacket(pending,{...bootstrapEnv,TELEGRAM_CHAT_ID:'-100123',TELEGRAM_APPROVER_IDS:'456'});assert(packet.text.includes(JSON.stringify(pending.corrected)));assert(packet.text.includes(pending.questionRevision));assert(packet.text.includes(REPORT_SOURCE_BASE));const {db,ledger}=store();ledger.transitionBound=(...args)=>ledger.transition(...args);ledger.releaseHead(initial);await ledger.receive(pending);await ledger.transition(pending.operationId,'received','delivering');await ledger.transition(pending.operationId,'delivering','pending_approval',{messageId:7,approval:packet.approval});const callback={id:'x',from:{id:456},message:{chat:{id:-100123},message_id:7},data:packet.callbackData};const row=ledger.get(pending.operationId);await assertApprovalCallback(row,callback,pending.operationId);
 for(const invalid of [{...callback,message:{...callback.message,message_id:999}},{...callback,data:'nr:'+pending.operationId},{...callback,data:packet.callbackData.slice(0,-1)+'x'},{...callback,message:{...callback.message,chat:{id:99}}}])await assert.rejects(assertApprovalCallback(row,invalid,pending.operationId),/STALE/);
 await assert.rejects(assertApprovalCallback({...row,updated_at:1},callback,pending.operationId),/STALE/);await assert.rejects(assertApprovalCallback({...row,result:JSON.stringify({messageId:7,approval:{...packet.approval,expiresAt:1}})},callback,pending.operationId),/STALE/);await assert.rejects(assertApprovalCallback({...row,payload:JSON.stringify({...pending,note:'changed'})},callback,pending.operationId),/STALE/);
 const env={REPORT_SOURCES_JSON:JSON.stringify([f.source]),REPORT_OPERATIONS:{getByName:()=>ledger},TELEGRAM_APPROVER_IDS:'456',TELEGRAM_CHAT_ID:'-100123',TELEGRAM_WEBHOOK_SECRET:'s',GITHUB_TOKEN:'synthetic',TELEGRAM_BOT_TOKEN:'synthetic'};const original=fetch;let writes=0,reads=0;globalThis.fetch=async(url,opts)=>{const u=new URL(url);if(u.hostname==='api.telegram.org')return Response.json({ok:true});if(opts.method!=='GET')writes++;reads++;if(u.pathname.endsWith('/git/ref/heads/main'))return Response.json({object:{sha:REPORT_SOURCE_BASE}});if(u.pathname.includes(f.source.sourcePath))return Response.json({content:Buffer.from(JSON.stringify(f.content)).toString('base64')});if(u.pathname.endsWith('/pulls'))return Response.json([{number:19,state:'open',base:{ref:'main',repo:{full_name:'shicheng0810/question-bank'}},head:{ref:'codex/report-'+pending.operationId,repo:{full_name:'shicheng0810/question-bank'},sha:'b'.repeat(40)}}]);return Response.json({content:Buffer.from(JSON.stringify({format:'qb-native-report-request-v1',baseCommit:REPORT_SOURCE_BASE,pending:publicCorrection(pending)})).toString('base64')});};
 const call=cb=>nativeReportWebhook({env,request:new Request('https://local',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'s'},body:JSON.stringify({callback_query:cb})})});try{await call({...callback,message:{...callback.message,message_id:999}});assert.equal(reads,0);await call(callback);assert.equal(ledger.get(pending.operationId).state,'pr_created');assert.equal(reads,5);await call(callback);assert.equal(reads,5);assert.equal(writes,0);}finally{globalThis.fetch=original;db.close();}
});
