import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,mkdir,writeFile,symlink,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {execFileSync} from 'node:child_process';
import {ReportLedger,validateReport} from '../functions/_shared/native-report.js';import {reportFixture} from './report-runtime/fixture.js';
import {approvalPacket,assertApprovalCallback,REPORT_SOURCE_BASE} from '../functions/_shared/report-approval.js';import {validateApprovalSource} from '../functions/_shared/native-report-publisher.js';
import {nativeReportWebhook} from '../functions/_shared/native-report-webhook.js';import {publicCorrection} from '../functions/_shared/public-report-contract.js';
import {onRequestPost as controlHTTP} from '../functions/api/report-control.js';import {inspectReportData,importReportData} from '../scripts/banks/report-data-import.mjs';import {readFile} from 'node:fs/promises';
const evidence=[];
function store(){const db=new DatabaseSync(':memory:');const ledger=new ReportLedger({sql:{exec(q,...v){const s=db.prepare(q),rows=s.columns().length?s.all(...v):(s.run(...v),[]);return {toArray:()=>rows};}}});ledger.transitionBound=(...a)=>ledger.transition(...a);ledger.releaseHead({commit:REPORT_SOURCE_BASE,pagesDeploymentId:crypto.randomUUID(),workerVersionId:crypto.randomUUID(),workerDeploymentId:crypto.randomUUID()});return {db,ledger};}
async function pendingFixture(){const f=await reportFixture(),{db,ledger}=store();const env={REPORT_SOURCES_JSON:JSON.stringify([f.source]),REPORT_OPERATIONS:{getByName:()=>ledger},TELEGRAM_BOT_TOKEN:'synthetic',TELEGRAM_CHAT_ID:'-100123',TELEGRAM_APPROVER_IDS:'456',TELEGRAM_WEBHOOK_SECRET:'synthetic-secret',GITHUB_TOKEN:'synthetic'};f.body.corrected={question:'Q'.repeat(800),choices:['A'.repeat(450),'B'.repeat(450)],answer:1};const pending=validateReport(f.body,[f.source]),packet=await approvalPacket(pending,env);await ledger.receive(pending);await ledger.transition(pending.operationId,'received','delivering');await ledger.transition(pending.operationId,'delivering','pending_approval',{messageId:7,approval:packet.approval});const cb={id:'x',from:{id:456},message:{chat:{id:-100123},message_id:7},data:packet.callbackData};return {f,db,ledger,env,pending,packet,cb};}
const callWebhook=(env,cb)=>nativeReportWebhook({env,request:new Request('https://local',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'synthetic-secret'},body:JSON.stringify({callback_query:cb})})});

test('legal complete correction approved once; wrong message/nonce/time/chat/payload blocked',async()=>{
 const {f,db,ledger,env,pending:p,packet,cb}=await pendingFixture(),row=ledger.get(p.operationId);assert(packet.text.includes(JSON.stringify(p.corrected)));assert(packet.text.includes(p.questionRevision));
 for(const change of [{message:{...cb.message,message_id:999}},{data:packet.callbackData.slice(0,-1)+'x'},{message:{...cb.message,chat:{id:99}}}])await assert.rejects(assertApprovalCallback(row,{...cb,...change},p.operationId),/STALE/);
 for(const altered of [{...row,updated_at:1},{...row,result:JSON.stringify({messageId:7,approval:{...packet.approval,expiresAt:1}})},{...row,payload:JSON.stringify({...p,note:'altered'})}])await assert.rejects(assertApprovalCallback(altered,cb,p.operationId),/STALE/);
 const original=fetch;let reads=0;globalThis.fetch=async(url,opts)=>{const u=new URL(url);if(u.hostname==='api.telegram.org')return Response.json({ok:true});reads++;assert.equal(opts.method,'GET');if(u.pathname.endsWith('/git/ref/heads/main'))return Response.json({object:{sha:REPORT_SOURCE_BASE}});if(u.pathname.includes(f.source.sourcePath))return Response.json({content:Buffer.from(JSON.stringify(f.content)).toString('base64')});if(u.pathname.endsWith('/pulls'))return Response.json([{number:19,state:'open',base:{ref:'main',repo:{full_name:'shicheng0810/question-bank'}},head:{ref:'codex/report-'+p.operationId,repo:{full_name:'shicheng0810/question-bank'},sha:'b'.repeat(40)}}]);return Response.json({content:Buffer.from(JSON.stringify({format:'qb-native-report-request-v1',baseCommit:REPORT_SOURCE_BASE,pending:publicCorrection(p)})).toString('base64')});};
 try{await callWebhook(env,{...cb,message:{...cb.message,message_id:999}});assert.equal(reads,0);await callWebhook(env,cb);assert.equal(ledger.get(p.operationId).state,'pr_created');assert.equal(reads,5);await callWebhook(env,cb);assert.equal(reads,5);evidence.push({case:'complete-approval',textLength:packet.text.length,approvedOnce:true,oldNegativesRejected:true});}finally{globalThis.fetch=original;db.close();}
});
test('R2 original race now rejects source advance before creating a blob',async()=>{
 const {f,db,ledger,env,pending,packet,cb}=await pendingFixture(),nextBase='b'.repeat(40);let sourceReads=0,publicBlob;const original=fetch;
 globalThis.fetch=async(url,opts)=>{const u=new URL(url),route=u.pathname;if(u.hostname==='api.telegram.org')return Response.json({ok:true});if(route.endsWith('/git/ref/heads/main'))return Response.json({object:{sha:++sourceReads===1?REPORT_SOURCE_BASE:nextBase}});if(route.includes(f.source.sourcePath))return Response.json({content:Buffer.from(JSON.stringify(f.content)).toString('base64')});if(route.endsWith('/pulls'))return Response.json(opts.method==='GET'?[]:{number:19,html_url:'https://github.invalid/19'});if(route.includes('/git/ref/heads/codex/report-')||route.includes('/protection/'))return new Response('{}',{status:404});if(route.endsWith('/git/blobs'))publicBlob=JSON.parse(JSON.parse(opts.body).content);return Response.json({sha:'c'.repeat(40),object:{sha:'c'.repeat(40)},tree:{sha:'d'.repeat(40)}});};
 try{await callWebhook(env,cb);assert.equal(ledger.get(pending.operationId).state,'conflict');assert.equal(publicBlob,undefined);evidence.push({case:'approval-base-race',approvedBase:packet.approval.sourceBase,PRBase:null,state:ledger.get(pending.operationId).state});}finally{globalThis.fetch=original;db.close();}
});
test('R2 continuity replay: approval follows controlled head and external source movement rejects',async()=>{
 const {body,source}=await reportFixture(),p=validateReport(body,[source]),env={TELEGRAM_CHAT_ID:'-100123',TELEGRAM_APPROVER_IDS:'456',REPORT_SOURCES_JSON:JSON.stringify([source]),GITHUB_TOKEN:'synthetic',REPORT_OPERATIONS:{getByName:()=>({releaseHead:()=>({commit:'b'.repeat(40),generation:1,inflight:null})})}};
 const packet=await approvalPacket(p,env),original=fetch;globalThis.fetch=async()=>Response.json({object:{sha:'c'.repeat(40)}});
 try{assert.equal(packet.approval.sourceBase,'b'.repeat(40));await assert.rejects(validateApprovalSource(env,p,packet.approval),/SOURCE_MOVED/);evidence.push({case:'Pages-source-pin',defaultBase:packet.approval.sourceBase,liveSource:'c'.repeat(40),result:'SOURCE_MOVED; adapter updates qb-do vars only'});}finally{globalThis.fetch=original;}
});
test('nested symlinks and FIFO rejected; valid regular tree admitted',async()=>{
 const root=await mkdtemp(path.join(process.cwd(),'reviewer-r3-nested-'));for(const d of ['content/nested','production-inputs','do-worker/src'])await mkdir(path.join(root,d),{recursive:true});await writeFile(path.join(root,'do-worker/src/reviewed-report-public-registry.generated.js'),'synthetic');
 await symlink('/tmp',path.join(root,'content/nested/escape'));await assert.rejects(inspectReportData(root),/SYMLINK/);await rm(path.join(root,'content/nested/escape'));
 execFileSync('mkfifo',[path.join(root,'content/nested/fifo')]);await assert.rejects(inspectReportData(root),/FILE_TYPE/);await rm(path.join(root,'content/nested/fifo'));
 assert.equal((await inspectReportData(root)).length,1);evidence.push({case:'nested-data',symlinkRejected:true,fifoRejected:true,validRegularTreeAdmitted:true});
});
test('R2 stale recovery and markers-only artifact attacks reject',async()=>{
 const {body,source}=await reportFixture(),{db,ledger}=store(),id=body.operationId;
 const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk={...await crypto.subtle.exportKey('jwk',pair.publicKey),kid:'synthetic',alg:'RS256'};
 const sha='a'.repeat(40),workflow='shicheng0810/question-bank/.github/workflows/report-publication.yml@refs/heads/main',aud='https://question-bank-78u.pages.dev/api/report-control',policy={audience:aud,workflowSha:sha,workflowPaths:[workflow]};
 const sign=async(runId)=>{const now=Math.floor(Date.now()/1000),enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),claims={iss:'https://token.actions.githubusercontent.com',aud,repository:'shicheng0810/question-bank',repository_id:'1164285871',repository_owner_id:'74512891',ref:'refs/heads/main',environment:'report-production',event_name:'workflow_dispatch',sub:'repo:shicheng0810/question-bank:environment:report-production',ref_type:'branch',job_workflow_sha:sha,job_workflow_ref:'shicheng0810/question-bank/.github/workflows/report-publication-executor.yml@'+sha,workflow_sha:sha,sha,workflow_ref:workflow,run_id:runId,run_attempt:'1',iat:now,nbf:now,exp:now+300,jti:'synthetic-'+runId},input=enc({alg:'RS256',kid:'synthetic'})+'.'+enc(claims);return input+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(input))).toString('base64url');};
 const deployment={deploymentId:crypto.randomUUID(),workerVersionId:crypto.randomUUID(),url:'https://12345678.question-bank-78u.pages.dev/',shortId:'12345678',resultCommit:'b'.repeat(40)},plan={operationId:id,prNumber:19,sourceCommit:REPORT_SOURCE_BASE,resultCommit:deployment.resultCommit,bankUid:body.bankUid,questionKey:body.questionKey,questionRevision:'e'.repeat(64),revision:'d'.repeat(64),contentHash:'d'.repeat(64),domain:'question-bank-78u.pages.dev',artifact:{manifest:[{path:'_worker.js',sha256:'f'.repeat(64)}],sha256:'c'.repeat(64)},controlJob:{operationId:id,runId:'1',runAttempt:'1',workflowSha:sha,runSha:sha,fence:1,issuedAt:Math.floor(Date.now()/1000)}};
 await ledger.receive(validateReport(body,[source]));for(const [a,b]of [['received','delivering'],['delivering','pending_approval'],['pending_approval','creating_pr'],['creating_pr','pr_created'],['pr_created','awaiting_deployment']])await ledger.transition(id,a,b,{});await ledger.transition(id,'awaiting_deployment','readback_pending',{plan,deployment});
 const env={GITHUB_TOKEN:'synthetic',REPORT_OIDC_POLICY_JSON:JSON.stringify(policy),REPORT_OPERATIONS:{getByName:()=>ledger}},old=await sign('1'),fresh=await sign('2'),original=fetch,urls=[];let markerMissing=true;
 globalThis.fetch=async url=>{urls.push(String(url));if(String(url).includes('/actions/runs/'))return Response.json({id:2,run_attempt:1,status:'in_progress',event:'workflow_dispatch',head_sha:sha,head_branch:'main',repository:{id:1164285871,owner:{id:74512891}},referenced_workflows:[{path:'shicheng0810/question-bank/.github/workflows/report-publication-executor.yml@'+sha,sha}],path:'.github/workflows/report-publication.yml'});if(String(url).includes('/.well-known/jwks'))return Response.json({keys:[jwk]});if(String(url).includes('/report-releases/'))return markerMissing?new Response('{}',{status:404}):Response.json(plan);if(String(url).endsWith('/banks/v2/manifest.json'))return Response.json({banks:[{bankUid:plan.bankUid,revision:plan.revision}]});throw Error('Unexpected provider code request');};
 const call=(token,action,extra={})=>controlHTTP({env,request:new Request(aud,{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify({operationId:id,action,fence:JSON.parse(ledger.get(id).result).controlJob?.fence||JSON.parse(ledger.get(id).result).plan.controlJob.fence,...extra})})}),binding={expectedResult:ledger.get(id).result,fence:1,...deployment,resultCommit:plan.resultCommit,artifactHash:plan.artifact.sha256,target:plan.domain},proof={artifactHash:plan.artifact.sha256,operationId:id,resultCommit:plan.resultCommit,contentHash:plan.contentHash,workerVersionId:deployment.workerVersionId,retainedRevisionsVerified:true,allPublishedBytesVerified:true};
 try{
  assert.equal((await call(fresh,'resumeReadback',{...binding,deploymentId:crypto.randomUUID()})).status,403);
  const responses=await Promise.all([call(fresh,'resumeReadback',binding),call(fresh,'resumeReadback',binding)]),values=await Promise.all(responses.map(r=>r.json()));assert(values.some(v=>v.resumed));
  assert.equal((await call(old,'readbackFailure')).status,403);
  const current=ledger.get(id);assert.equal((await call(old,'resumeReadback',{...binding,expectedResult:current.result,fence:2})).status,403);assert.equal(JSON.parse(ledger.get(id).result).plan.controlJob.runId,'2');
  markerMissing=false;assert.equal((await call(fresh,'readback',{proof})).status,409);assert.equal(ledger.get(id).state,'readback_failed');assert.equal((await (await call(fresh,'sendReceipt')).json()).blocked,true);
  assert.equal(urls.some(u=>u.includes('/workers/scripts/')||u.includes('_worker.js')),false);
  evidence.push({case:'recovery-and-artifact',oldRunRecoveryRejected:true,unprovenArtifactRejected:true,state:ledger.get(id).state,limits:'Synthetic signed WebCrypto + actual SQLite handler; no external provider executed.'});
 }finally{globalThis.fetch=original;db.close();}
});
test('legal exact Git blob importer succeeds; dirty tree cannot replace trusted data',async()=>{
 const root=await mkdtemp(path.join(process.cwd(),'reviewer-r3-import-')),trustedRoot=path.join(root,'trusted'),dataRoot=path.join(root,'proposed'),requestPath='content/report-requests/'+crypto.randomUUID()+'.json';
 for(const tree of [trustedRoot,dataRoot]){for(const dir of ['content','production-inputs','do-worker/src','scripts'])await mkdir(path.join(tree,dir),{recursive:true});await writeFile(path.join(tree,'content/data.json'),'{"old":true}');await writeFile(path.join(tree,'production-inputs/index.json'),'{}');await writeFile(path.join(tree,'do-worker/src/reviewed-report-public-registry.generated.js'),'export const value=[];');await writeFile(path.join(tree,'scripts/trust.js'),tree===trustedRoot?'TRUSTED':'PROPOSED');}
 await writeFile(path.join(dataRoot,'content/data.json'),'{"new":true}');await mkdir(path.dirname(path.join(dataRoot,requestPath)),{recursive:true});await writeFile(path.join(dataRoot,requestPath),'{}');
 const git=(...args)=>execFileSync('git',args,{cwd:dataRoot,encoding:'utf8'}).trim();git('init','--quiet');git('add','.');git('-c','user.name=Local Review','-c','user.email=review@example.invalid','commit','--quiet','-m','synthetic clean data');const expectedCommit=git('rev-parse','HEAD'),args={trustedRoot,dataRoot,expectedCommit,requestPath,verified:{files:['content/data.json']}};
 await importReportData(args);assert.equal(await readFile(path.join(trustedRoot,'content/data.json'),'utf8'),'{"new":true}');assert.equal(await readFile(path.join(trustedRoot,'scripts/trust.js'),'utf8'),'TRUSTED');
 await writeFile(path.join(dataRoot,'content/data.json'),'DIRTY');await assert.rejects(importReportData(args),/WORKTREE_DIRTY/);assert.equal(await readFile(path.join(trustedRoot,'content/data.json'),'utf8'),'{"new":true}');evidence.push({case:'Git-import',legalImportPassed:true,dirtyImportDenied:true,proposedScriptsNotCopied:true});
});
test.after(async()=>writeFile('reviewer-r3-extra-evidence.json',JSON.stringify(evidence,null,2)+'\n'));
