import {env, SELF, fetchMock, runInDurableObject, runDurableObjectAlarm} from 'cloudflare:test';
import {it, expect, beforeEach, afterEach} from 'vitest';
import {identityHash,randomHex,randomNonce,IDENTITY_PREFIX,IDENTITY_SEED_PREFIX} from '../../functions/_shared/report-identity-challenge.js';
import {RELEASE_HEAD} from '../../functions/_shared/report-release-contract.js';
import {reportFixture} from './fixture.js';
import {validateReport} from '../../functions/_shared/native-report.js';
beforeEach(()=>{fetchMock.activate();fetchMock.disableNetConnect();});
afterEach(()=>{fetchMock.assertNoPendingInterceptors();fetchMock.deactivate();});
const tg=()=>fetchMock.get('https://api.telegram.org');
const message={message_id:71,chat:{id:-100123},from:{id:888,is_bot:true}};
async function fixture(){const id=randomHex(16),cap=randomHex(32),now=Date.now(),seed={schema:1,challengeId:id,capHash:await identityHash(cap),nonce:randomNonce(),chatId:'-100123',createdAt:now,expiresAt:now+600000};await env.EDITS.put(IDENTITY_SEED_PREFIX+id,JSON.stringify(seed));return {id,cap,seed,stub:env.REPORT_OPERATIONS.getByName(IDENTITY_PREFIX+id)};}
const api=(f,action,extra={},cap=f.cap)=>SELF.fetch('https://local/api/report-identity-challenge',{method:'POST',headers:{authorization:'Bearer '+cap},body:JSON.stringify({action,challengeId:f.id,...extra})});
const status=async f=>(await api(f,'status')).json();
function mockStart(){tg().intercept({path:'/botlocal-fake/sendMessage',method:'POST',body:value=>{const v=JSON.parse(value);return v.chat_id==='-100123' && !v.reply_markup && v.text.includes('TEST');}}).reply(200,{ok:true,result:message});tg().intercept({path:'/botlocal-fake/editMessageReplyMarkup',method:'POST',body:value=>{const v=JSON.parse(value);return v.message_id===71 && new TextEncoder().encode(v.reply_markup.inline_keyboard[0][0].callback_data).length<=64;}}).reply(200,{ok:true,result:message});}
async function armed(){const f=await fixture();mockStart();expect((await (await api(f,'start')).json()).state).toBe('armed');return f;}
const callback=(f,extra={})=>({id:'q-'+randomHex(8),from:{id:999,is_bot:false},message,...extra,data:extra.data??`ti:${f.id}:${f.seed.nonce}`});
const webhook=(cb,secret='local-secret')=>SELF.fetch('https://local/api/tg-webhook',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':secret},body:JSON.stringify({callback_query:cb})});
function mockPopup(reply={ok:true,result:true}){const seen={};tg().intercept({path:'/botlocal-fake/answerCallbackQuery',method:'POST'}).reply(options=>{const body=JSON.parse(options.body);seen.code=body.text.match(/[A-F0-9]{4}-[A-F0-9]{4}/)?.[0];seen.queryId=body.callback_query_id;seen.private=body.show_alert===true && body.cache_time===0;return {statusCode:200,data:JSON.stringify(reply)};});return seen;}
async function ageRow(f,field){await runInDurableObject(f.stub,async(instance,state)=>{const row=[...state.storage.sql.exec('SELECT value FROM report_identity_challenge WHERE id = ?',f.id)][0];const value=JSON.parse(row.value);value[field]=Date.now()-1;state.storage.sql.exec('UPDATE report_identity_challenge SET value = ? WHERE id = ?',JSON.stringify(value),f.id);});}

it('concurrent HTTP start sends exactly one TEST and binds exact Message before button; retry no send',async()=>{const f=await fixture();mockStart();const results=await Promise.all([api(f,'start'),api(f,'start')]);for(const r of results)expect(r.status).toBe(200);expect((await status(f)).state).toBe('armed');expect((await (await api(f,'start')).json()).state).toBe('armed');});
it('fixed owner chat selector resolves only inside runtime; prepared chat drift cannot cause send',async()=>{const f=await fixture();await env.EDITS.put(IDENTITY_SEED_PREFIX+f.id,JSON.stringify({...f.seed,chatId:'configured-report-chat'}));mockStart();expect((await (await api(f,'start')).json()).state).toBe('armed');const seen=mockPopup();await webhook(callback(f));expect((await (await api(f,'confirm',{code:seen.code})).json()).receipt.chatId).toBe('-100123');const g=await fixture();await g.stub.identityChallenge(g.id,'prepare',{seed:{...g.seed,chatId:'-999'}});await env.EDITS.put(IDENTITY_SEED_PREFIX+g.id,JSON.stringify({...g.seed,chatId:'configured-report-chat'}));expect((await api(g,'start')).status).toBe(403);expect((await g.stub.identityChallenge(g.id,'status',{capHash:g.seed.capHash})).state).toBe('prepared');});
it('unknown send is terminal across retries and never exposes a button',async()=>{const f=await fixture();tg().intercept({path:'/botlocal-fake/sendMessage',method:'POST'}).replyWithError(new Error('synthetic timeout'));expect((await (await api(f,'start')).json()).state).toBe('send_unknown');expect((await (await api(f,'start')).json()).state).toBe('send_unknown');await webhook(callback(f));expect((await status(f)).state).toBe('send_unknown');});
it('crash after pre-I/O CAS and early click before exact markup acknowledgment fail closed without I/O retry',async()=>{const f=await fixture();await f.stub.identityChallenge(f.id,'prepare',{seed:f.seed});expect((await f.stub.identityChallenge(f.id,'beginSend',{capHash:f.seed.capHash})).accepted).toBe(true);expect((await (await api(f,'start')).json()).state).toBe('sending');await f.stub.identityChallenge(f.id,'bind',{capHash:f.seed.capHash,messageId:71,chatId:'-100123',botId:'888'});await f.stub.identityChallenge(f.id,'beginExpose',{capHash:f.seed.capHash});await webhook(callback(f));expect((await status(f)).state).toBe('exposing');expect((await (await api(f,'start')).json()).state).toBe('exposing');});
it('provider wrong chat/message/bot and non-OK response cannot bind or expose',async()=>{for(const wrong of [{...message,chat:{id:-100999}},{...message,message_id:0},{...message,from:{id:888,is_bot:false}},null]){const f=await fixture();tg().intercept({path:'/botlocal-fake/sendMessage',method:'POST'}).reply(200,{ok:true,result:wrong});expect((await (await api(f,'start')).json()).state).toBe('send_unknown');expect((await (await api(f,'start')).json()).state).toBe('send_unknown');}const f=await fixture();tg().intercept({path:'/botlocal-fake/sendMessage',method:'POST'}).reply(500,{ok:true,result:message});expect((await (await api(f,'start')).json()).state).toBe('send_unknown');});
it('unknown or wrong markup response is terminal; retry and callback cannot advance',async()=>{for(const wrong of [null,{...message,message_id:72}]){const f=await fixture();tg().intercept({path:'/botlocal-fake/sendMessage',method:'POST'}).reply(200,{ok:true,result:message});tg().intercept({path:'/botlocal-fake/editMessageReplyMarkup',method:'POST'}).reply(200,{ok:true,result:wrong});expect((await (await api(f,'start')).json()).state).toBe('visibility_unknown');await webhook(callback(f));expect((await (await api(f,'start')).json()).state).toBe('visibility_unknown');}});
it('secret, wrong message/chat/nonce/bot, inline/forwarded/bot-user and malformed ti all reject without I/O',async()=>{const f=await armed();const good=callback(f);expect((await webhook(good,'wrong')).status).toBe(403);const wrong=[{...good,message:{...message,message_id:72}},{...good,message:{...message,chat:{id:-999}}},{...good,message:{...message,from:{id:889,is_bot:true}}},{...good,message:{...message,from:{id:888,is_bot:false}}},{...good,data:`ti:${f.id}:${randomNonce()}`},{...good,inline_message_id:'inline'},{...good,message:{...message,forward_origin:{type:'user'}}},{...good,from:{id:999,is_bot:true}},{...good,from:{id:0,is_bot:false}},{...good,data:'ti:nr:bad'}];for(const cb of wrong)expect((await webhook(cb)).status).toBe(200);expect((await status(f)).state).toBe('armed');});
it('parallel unknown-approver clicks yield one candidate; current conversation code alone confirms and replay is idempotent',async()=>{const f=await armed(),seen=mockPopup(),a=callback(f),b=callback(f,{from:{id:1000,is_bot:false}});await Promise.all([webhook(a),webhook(b)]);expect(seen.private).toBe(true);expect(typeof seen.code==='string').toBe(true);const waiting=await status(f);expect(waiting.state).toBe('awaiting_confirmation');expect('receipt' in waiting || 'candidateId' in waiting || 'codeHash' in waiting || 'capHash' in waiting || 'queryId' in waiting).toBe(false);expect((await api(f,'confirm',{code:'0000-0000'})).status).toBe(403);const receipt=await (await api(f,'confirm',{code:seen.code})).json();expect(receipt.state).toBe('confirmed');expect(receipt.receipt.telegramUserId === (seen.queryId===a.id?'999':'1000')).toBe(true);expect(receipt.receipt.authorityGranted).toBe(false);await webhook(a);await webhook(b);expect((await (await api(f,'confirm',{code:seen.code})).json()).receipt.confirmedAt).toBe(receipt.receipt.confirmedAt);expect((await api(f,'confirm',{code:'0000-0000'})).status).toBe(403);});
it('unknown private-popup outcome cannot confirm even when the user has the code; no resend on callback replay',async()=>{const f=await armed(),seen=mockPopup({ok:true,result:false}),cb=callback(f);await webhook(cb);expect((await status(f)).state).toBe('answer_unknown');expect((await api(f,'confirm',{code:seen.code})).status).toBe(403);await webhook(cb);expect((await status(f)).state).toBe('answer_unknown');});
it('wrong capability, missing seed, expired seed, rotated KV seed cannot start or reset the state',async()=>{const f=await fixture();expect((await api(f,'start',{},randomHex(32))).status).toBe(403);await env.EDITS.delete(IDENTITY_SEED_PREFIX+f.id);expect((await api(f,'start')).status).toBe(403);await env.EDITS.put(IDENTITY_SEED_PREFIX+f.id,JSON.stringify({...f.seed,createdAt:Date.now()-2000,expiresAt:Date.now()-1000}));expect((await api(f,'start')).status).toBe(403);await env.EDITS.put(IDENTITY_SEED_PREFIX+f.id,JSON.stringify(f.seed));mockStart();await api(f,'start');const rotated=randomHex(32);await env.EDITS.put(IDENTITY_SEED_PREFIX+f.id,JSON.stringify({...f.seed,capHash:await identityHash(rotated)}));expect((await api(f,'start',{},rotated)).status).toBe(403);expect((await f.stub.identityChallenge(f.id,'status',{capHash:f.seed.capHash})).state).toBe('armed');});
it('expired DO or short code refuses callback/confirmation and alarm erases candidate secrets',async()=>{const f=await armed();await ageRow(f,'expiresAt');await webhook(callback(f));expect((await api(f,'status')).status).toBe(403);const g=await armed(),seen=mockPopup();await webhook(callback(g));await ageRow(g,'codeExpiresAt');expect((await api(g,'confirm',{code:seen.code})).status).toBe(403);await runDurableObjectAlarm(g.stub);const sanitized=await runInDurableObject(g.stub,async(instance,state)=>{const row=JSON.parse([...state.storage.sql.exec('SELECT value FROM report_identity_challenge WHERE id = ?',g.id)][0].value);return {state:row.state,keys:Object.keys(row).sort()};});expect(sanitized).toEqual({state:'expired',keys:['challengeId','expiresAt','state']});});
it('three wrong current-session codes lock permanently against a later correct reply',async()=>{const f=await armed(),seen=mockPopup();await webhook(callback(f));for(let i=0;i<3;i++)expect((await api(f,'confirm',{code:seen.code==='0000-0000'?'1111-1111':'0000-0000'})).status).toBe(403);expect((await status(f)).state).toBe('confirmation_locked');expect((await api(f,'confirm',{code:seen.code})).status).toBe(403);});
it('challenge requests cannot add chat/user/admin/gate input and wrong DO namespace rejects',async()=>{const f=await fixture();for(const extra of [{chatId:'-999'},{telegramUserId:'456'},{operationId:crypto.randomUUID()},{gate:true}])expect((await api(f,'start',extra)).status).toBe(400);expect((await api(f,'deploy')).status).toBe(400);await expect(env.REPORT_OPERATIONS.getByName(crypto.randomUUID()).identityChallenge(f.id,'prepare',{seed:f.seed})).rejects.toThrow('REPORT_OPERATION_BINDING_INVALID');});
it('no-op identity preserves actual Report row and release-head CAS data and leaves approver allowlist unchanged',async()=>{const {body,source}=await reportFixture(),report=env.REPORT_OPERATIONS.getByName(body.operationId);await report.receive(validateReport(body,[source]));const before=await report.get(body.operationId),head=env.REPORT_OPERATIONS.getByName(RELEASE_HEAD),headBefore=await head.releaseHead();const f=await armed(),seen=mockPopup();await webhook(callback(f));const result=await (await api(f,'confirm',{code:seen.code})).json();expect(result.receipt.authorityGranted).toBe(false);expect(await report.get(body.operationId)).toEqual(before);expect(await head.releaseHead()).toEqual(headBefore);expect(env.TELEGRAM_APPROVER_IDS).toBe('456');const forged=callback(f,{data:'ti:nr:'+body.operationId});await webhook(forged);expect(await report.get(body.operationId)).toEqual(before);});
