import {env,SELF,fetchMock} from 'cloudflare:test';import {it,expect,beforeEach,afterEach} from 'vitest';import {reportFixture} from './fixture.js';import {RELEASE_HEAD} from '../../functions/_shared/report-release-contract.js';
import {validateReport} from '../../functions/_shared/native-report.js';
beforeEach(()=>{fetchMock.activate();fetchMock.disableNetConnect();});afterEach(()=>{fetchMock.assertNoPendingInterceptors();fetchMock.deactivate();});
const workflow='shicheng0810/question-bank-source/.github/workflows/report-publication.yml@refs/heads/main';
async function signing(){const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk={...await crypto.subtle.exportKey('jwk',pair.publicKey),kid:'local-synthetic',alg:'RS256',use:'sig'};return {pair,jwk};}
const encode=value=>btoa(typeof value==='string'?value:JSON.stringify(value)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
async function token(pair,run='2'){const now=Math.floor(Date.now()/1000),claims={iss:'https://token.actions.githubusercontent.com',aud:'https://question-bank-78u.pages.dev/api/report-control',repository:'shicheng0810/question-bank-source',repository_id:'1403515803',repository_owner_id:'74512891',ref:'refs/heads/main',environment:'report-production',event_name:'workflow_dispatch',sub:'repo:shicheng0810/question-bank-source:environment:report-production',workflow_sha:'a'.repeat(40),sha:'a'.repeat(40),workflow_ref:workflow,run_id:run,run_attempt:'1',iat:now,nbf:now,exp:now+300,jti:crypto.randomUUID()};const input=encode({alg:'RS256',kid:'local-synthetic'})+'.'+encode(claims),sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(input)));return input+'.'+encode(String.fromCharCode(...sig));}
const call=(auth,body)=>SELF.fetch('https://local/api/report-control',{method:'POST',headers:{authorization:'Bearer '+auth},body:JSON.stringify(body)});
it('independent replay: old run/attempt/snapshot recovery rejected in real SQLite DO HTTP',async()=>{
 const {body,source}=await reportFixture(),id=body.operationId,stub=env.REPORT_OPERATIONS.getByName(id);await stub.receive(validateReport(body,[source]));for(const [a,b] of [['received','delivering'],['delivering','pending_approval'],['pending_approval','creating_pr'],['creating_pr','pr_created'],['pr_created','awaiting_deployment']])await stub.transition(id,a,b,{});
 const deployment={deploymentId:crypto.randomUUID(),workerVersionId:crypto.randomUUID(),shortId:'12345678',url:'https://12345678.question-bank-78u.pages.dev/',resultCommit:'b'.repeat(40)},plan={operationId:id,resultCommit:'b'.repeat(40),domain:'question-bank-78u.pages.dev',artifact:{sha256:'c'.repeat(64)},controlJob:{operationId:id,runId:'1',runAttempt:'1',workflowSha:'a'.repeat(40),issuedAt:Math.floor(Date.now()/1000),fence:1}};await stub.transition(id,'awaiting_deployment','readback_pending',{plan,deployment});
 const {pair,jwk}=await signing(),input={operationId:id,action:'resumeReadback',expectedResult:(await stub.get(id)).result,fence:1,...deployment,resultCommit:plan.resultCommit,target:plan.domain,artifactHash:plan.artifact.sha256};const keys=()=>fetchMock.get('https://token.actions.githubusercontent.com').intercept({path:'/.well-known/jwks',method:'GET'}).reply(200,{keys:[jwk]});
 fetchMock.get('https://api.github.com').intercept({path:'/repos/shicheng0810/question-bank-source/actions/runs/2',method:'GET'}).reply(200,{id:2,run_attempt:1,status:'in_progress',event:'workflow_dispatch',head_sha:'a'.repeat(40),path:'.github/workflows/report-publication.yml'});
 fetchMock.get('https://api.github.com').intercept({path:'/repos/shicheng0810/question-bank-source/actions/runs/2/attempts/1',method:'GET'}).reply(200,{id:2,run_attempt:1,status:'in_progress',event:'workflow_dispatch',head_sha:'a'.repeat(40),path:'.github/workflows/report-publication.yml'});
 keys();expect((await (await call(await token(pair,'2'),input)).json()).resumed).toBe(true);expect(JSON.parse((await stub.get(id)).result).plan.controlJob.runId).toBe('2');
 keys();expect((await call(await token(pair,'1'),{operationId:id,action:'readbackFailure'})).status).toBe(403);
 const latest=await stub.get(id);keys();expect((await call(await token(pair,'1'),{...input,expectedResult:latest.result,fence:2})).status).toBe(403);expect(JSON.parse((await stub.get(id)).result).plan.controlJob.runId).toBe('2');
 keys();expect((await call(await token(pair,'2'),input)).status).toBe(403);
 keys();expect((await call(await token(pair,'2'),{...input,expectedResult:latest.result,fence:2})).status).toBe(403);
});

it('real SQLite production-head CAS advances twice, stale head rejected and bootstrap cannot overwrite',async()=>{
 const head=env.REPORT_OPERATIONS.getByName(RELEASE_HEAD),first=await head.releaseHead();expect(first.commit).toBe('9aa96ebdef680e580c4cdbc232f6a0de82d65071');
 const locked={...first,inflight:{operationId:crypto.randomUUID()}};expect(await head.releaseCAS(first,locked)).toBe(true);expect(await head.releaseCAS(first,{...first,commit:'f'.repeat(40)})).toBe(false);
 const second={...locked,inflight:null,commit:'b'.repeat(40),generation:1};expect(await head.releaseCAS(locked,second)).toBe(true);
 const third={...second,commit:'c'.repeat(40),generation:2};expect(await head.releaseCAS(second,third)).toBe(true);expect((await head.releaseHead()).commit).toBe('c'.repeat(40));expect(await head.releaseCAS(third,first)).toBe(true);
});
