import {env,SELF,fetchMock} from 'cloudflare:test';import {it,expect,beforeEach,afterEach} from 'vitest';import {reportFixture} from './fixture.js';import {validateReport} from '../../functions/_shared/native-report.js';
beforeEach(()=>{fetchMock.activate();fetchMock.disableNetConnect();});afterEach(()=>{fetchMock.assertNoPendingInterceptors();fetchMock.deactivate();});
const workflow='shicheng0810/question-bank/.github/workflows/report-publication.yml@refs/heads/main';
async function signing(){const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk={...await crypto.subtle.exportKey('jwk',pair.publicKey),kid:'local-synthetic',alg:'RS256',use:'sig'};return {pair,jwk};}
const encode=value=>btoa(typeof value==='string'?value:JSON.stringify(value)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
async function token(pair,run='2'){const now=Math.floor(Date.now()/1000),claims={iss:'https://token.actions.githubusercontent.com',aud:'https://question-bank-78u.pages.dev/api/report-control',repository:'shicheng0810/question-bank',repository_id:'1164285871',repository_owner_id:'74512891',ref:'refs/heads/main',environment:'report-production',event_name:'workflow_dispatch',sub:'repo:shicheng0810/question-bank:environment:report-production',workflow_sha:'a'.repeat(40),sha:'a'.repeat(40),workflow_ref:workflow,run_id:run,run_attempt:'1',iat:now,nbf:now,exp:now+300,jti:crypto.randomUUID()};const input=encode({alg:'RS256',kid:'local-synthetic'})+'.'+encode(claims),sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(input)));return input+'.'+encode(String.fromCharCode(...sig));}
const call=(auth,body)=>SELF.fetch('https://local/api/report-control',{method:'POST',headers:{authorization:'Bearer '+auth},body:JSON.stringify(body)});
it('real HTTP recovery CAS binds exact recorded artifact/deployment, rejects late owner and retains failed missing readback',async()=>{
 const {body,source}=await reportFixture(),id=body.operationId,stub=env.REPORT_OPERATIONS.getByName(id);await stub.receive(validateReport(body,[source]));for(const [a,b] of [['received','delivering'],['delivering','pending_approval'],['pending_approval','creating_pr'],['creating_pr','pr_created'],['pr_created','awaiting_deployment']])await stub.transition(id,a,b,{});
 const deployment={deploymentId:crypto.randomUUID(),workerVersionId:crypto.randomUUID(),shortId:'12345678',url:'https://12345678.question-bank-78u.pages.dev/',resultCommit:'b'.repeat(40)},plan={operationId:id,resultCommit:'b'.repeat(40),domain:'question-bank-78u.pages.dev',artifact:{sha256:'c'.repeat(64)},controlJob:{operationId:id,runId:'1',runAttempt:'1',workflowSha:'a'.repeat(40),issuedAt:Math.floor(Date.now()/1000),fence:1}};await stub.transition(id,'awaiting_deployment','readback_pending',{plan,deployment});
 const {pair,jwk}=await signing(),auth=await token(pair),input={operationId:id,action:'resumeReadback',expectedResult:(await stub.get(id)).result,fence:1,...deployment,resultCommit:plan.resultCommit,target:plan.domain,artifactHash:plan.artifact.sha256};const keys=()=>fetchMock.get('https://token.actions.githubusercontent.com').intercept({path:'/.well-known/jwks',method:'GET'}).reply(200,{keys:[jwk]});
 keys();expect((await call(auth,{...input,target:'other.invalid'})).status).toBe(403);expect((await stub.get(id)).state).toBe('readback_pending');
 fetchMock.get('https://api.github.com').intercept({path:'/repos/shicheng0810/question-bank/actions/runs/2',method:'GET'}).reply(200,{id:2,run_attempt:1,status:'in_progress',event:'workflow_dispatch',head_sha:'a'.repeat(40),path:'.github/workflows/report-publication.yml'}).times(2);
 fetchMock.get('https://api.github.com').intercept({path:'/repos/shicheng0810/question-bank/actions/runs/2/attempts/1',method:'GET'}).reply(200,{id:2,run_attempt:1,status:'in_progress',event:'workflow_dispatch',head_sha:'a'.repeat(40),path:'.github/workflows/report-publication.yml'}).times(2);
 keys();keys();const responses=await Promise.all([call(auth,input),call(auth,input)]),values=await Promise.all(responses.map(r=>r.json()));expect(values.filter(v=>v.resumed)).toHaveLength(1);
 keys();expect((await call(await token(pair,'1'),{operationId:id,action:'readbackFailure'})).status).toBe(403);
 keys();const response=await call(auth,{operationId:id,action:'readback',fence:2,proof:{artifactHash:plan.artifact.sha256,operationId:id,resultCommit:plan.resultCommit,contentHash:plan.contentHash,workerVersionId:deployment.workerVersionId,retainedRevisionsVerified:true,allPublishedBytesVerified:true}});expect(response.status).toBe(409);expect((await stub.get(id)).state).toBe('readback_failed');
 keys();expect((await (await call(auth,{operationId:id,action:'sendReceipt',fence:2})).json()).blocked).toBe(true);
 const failed=await stub.get(id);await stub.transitionBound(id,'readback_failed','reconciling_readback',JSON.parse(failed.result),failed.result);await stub.transition(id,'reconciling_readback','readback_pending',JSON.parse(failed.result));const receipt={...JSON.parse(failed.result).plan,...deployment,readbackVerified:true};await stub.transition(id,'readback_pending','receipt_pending',receipt);
 keys();expect((await call(auth,{...input,action:'resumeReceipt',deploymentId:crypto.randomUUID()})).status).toBe(403);expect((await stub.get(id)).state).toBe('receipt_pending');
 const snapshot=await stub.get(id);fetchMock.get('https://api.github.com').intercept({path:'/repos/shicheng0810/question-bank/actions/runs/3',method:'GET'}).reply(200,{id:3,run_attempt:1,status:'in_progress',event:'workflow_dispatch',head_sha:'a'.repeat(40),path:'.github/workflows/report-publication.yml'});
 fetchMock.get('https://api.github.com').intercept({path:'/repos/shicheng0810/question-bank/actions/runs/3/attempts/1',method:'GET'}).reply(200,{id:3,run_attempt:1,status:'in_progress',event:'workflow_dispatch',head_sha:'a'.repeat(40),path:'.github/workflows/report-publication.yml'});
 keys();expect((await (await call(await token(pair,'3'),{...input,action:'resumeReceipt',expectedResult:snapshot.result,fence:2})).json()).resumed).toBe(true);
 keys();expect((await call(await token(pair,'1'),{operationId:id,action:'sendReceipt',fence:2})).status).toBe(403);expect((await stub.get(id)).state).toBe('receipt_pending');

});
