import { publicCorrection } from '../../functions/_shared/public-report-contract.js';
import { env, SELF, fetchMock } from 'cloudflare:test';
import { beforeEach,afterEach,it,expect } from 'vitest';
import { reportFixture } from './fixture.js';
import { validateReport } from '../../functions/_shared/native-report.js';
import { reconcileNativeReportPR } from '../../functions/_shared/native-report-publisher.js';
import { inspectNativeReportOperation } from '../../functions/_shared/native-report-inspection.js';
beforeEach(()=>{fetchMock.activate();fetchMock.disableNetConnect();});
afterEach(()=>{fetchMock.assertNoPendingInterceptors();fetchMock.deactivate();});
const tg=()=>fetchMock.get('https://api.telegram.org');
function mockExistingPR(body,pending,number){const prefix='/repos/shicheng0810/question-bank-source',repo={full_name:'shicheng0810/question-bank-source'},sha='b'.repeat(40);const gh=fetchMock.get('https://api.github.com');gh.intercept({path:prefix+'/pulls?state=all&head=shicheng0810:codex/report-'+body.operationId,method:'GET'}).reply(200,[{number,html_url:'https://github.test/'+number,state:'open',base:{ref:'source',repo},head:{ref:'codex/report-'+body.operationId,repo,sha}}]);gh.intercept({path:prefix+'/contents/content/report-requests/'+body.operationId+'.json?ref='+sha,method:'GET'}).reply(200,{content:btoa(JSON.stringify({format:'qb-native-report-request-v1',baseCommit:'a'.repeat(40),pending:publicCorrection(pending)}))});}
const callback=(id,from=456)=>({callback_query:{id:'callback-test',from:{id:from},message:{chat:{id:-100123},message_id:7},data:'nr:'+id}});
const webhook=body=>SELF.fetch('https://local/api/tg-webhook',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'local-secret','content-type':'application/json'},body:JSON.stringify(body)});
it('actual DO RPC admits identical retries and single concurrent CAS',async()=>{const {body,source}=await reportFixture(),pending=validateReport(body,[source]),stub=env.REPORT_OPERATIONS.getByName(body.operationId);await Promise.all([stub.receive(pending),stub.receive(pending)]);const claims=await Promise.all([stub.transition(body.operationId,'received','delivering'),stub.transition(body.operationId,'received','delivering')]);expect(claims.filter(Boolean)).toHaveLength(1);expect((await stub.get(body.operationId)).state).toBe('delivering');});
it('rejects forged operation ID through a differently named real DO',async()=>{const {body,source}=await reportFixture();await expect(env.REPORT_OPERATIONS.getByName(crypto.randomUUID()).receive(validateReport(body,[source]))).rejects.toThrow('REPORT_OPERATION_BINDING_INVALID');});
it('HTTP duplicate feedback sends provider only once and retains public payload',async()=>{const {body}=await reportFixture();tg().intercept({path:'/botlocal-fake/sendMessage',method:'POST'}).reply(200,{ok:true,result:{message_id:7}});const submit=()=>SELF.fetch('https://local/api/feedback',{method:'POST',body:JSON.stringify(body)});const responses=await Promise.all([submit(),submit()]);for(const response of responses)expect((await response.json()).stored).toBe(true);expect((await env.REPORT_OPERATIONS.getByName(body.operationId).get(body.operationId)).state).toBe('pending_approval');});
it('provider transport timeout remains unknown and HTTP retry does not resend',async()=>{const {body}=await reportFixture();tg().intercept({path:'/botlocal-fake/sendMessage',method:'POST'}).replyWithError(new Error('timeout'));const submit=()=>SELF.fetch('https://local/api/feedback',{method:'POST',body:JSON.stringify(body)});expect((await (await submit()).json()).delivered).toBe(false);expect((await (await submit()).json()).state).toBe('delivery_unknown');});
it('HTTP webhook secret cannot be missing and wrong approver never touches GitHub',async()=>{const bad=await SELF.fetch('https://local/api/tg-webhook',{method:'POST',body:'{}'});expect(bad.status).toBe(403);tg().intercept({path:'/botlocal-fake/answerCallbackQuery',method:'POST'}).reply(200,{ok:true});expect((await webhook(callback(crypto.randomUUID(),999))).status).toBe(200);});
it('duplicate actual webhook with existing PR creates no branch or second PR',async()=>{const {body,source}=await reportFixture(),pending=validateReport(body,[source]),stub=env.REPORT_OPERATIONS.getByName(body.operationId);await stub.receive(pending);await stub.transition(body.operationId,'received','delivering');await stub.transition(body.operationId,'delivering','pending_approval');mockExistingPR(body,pending,19);tg().intercept({path:'/botlocal-fake/answerCallbackQuery',method:'POST'}).reply(200,{ok:true}).times(2);tg().intercept({path:'/botlocal-fake/editMessageReplyMarkup',method:'POST'}).reply(200,{ok:true});await Promise.all([webhook(callback(body.operationId)),webhook(callback(body.operationId))]);const row=await stub.get(body.operationId);expect(row.state).toBe('pr_created');expect(JSON.parse(row.result).number).toBe(19);});
it('cannot publish before awaiting-deployment and receipt',async()=>{const {body,source}=await reportFixture(),stub=env.REPORT_OPERATIONS.getByName(body.operationId);await stub.receive(validateReport(body,[source]));await expect(stub.transition(body.operationId,'received','published',{})).rejects.toThrow('REPORT_TRANSITION_INVALID');});
it('actual webhook reconciles a timed-out pull without performing another write',async()=>{const {body,source}=await reportFixture(),stub=env.REPORT_OPERATIONS.getByName(body.operationId);await stub.receive(validateReport(body,[source]));await stub.transition(body.operationId,'received','delivering');await stub.transition(body.operationId,'delivering','pending_approval');await stub.transition(body.operationId,'pending_approval','creating_pr');await stub.transition(body.operationId,'creating_pr','provider_unknown');mockExistingPR(body,validateReport(body,[source]),77);tg().intercept({path:'/botlocal-fake/answerCallbackQuery',method:'POST'}).reply(200,{ok:true});await webhook(callback(body.operationId));expect((await stub.get(body.operationId)).state).toBe('pr_created');});
it('legacy callback reads retained real KV and reports manual review without deletion',async()=>{const key='edit:0123456789abcdef';await env.EDITS.put(key,JSON.stringify({original:{question:'legacy'},corrected:{question:'fix'}}));tg().intercept({path:'/botlocal-fake/answerCallbackQuery',method:'POST',body:body=>body.includes('旧报告已保留')}).reply(200,{ok:true});const body=callback(crypto.randomUUID());body.callback_query.data='ap:0123456789abcdef';await webhook(body);expect(await env.EDITS.get(key)).not.toBeNull();});
it('timed-out branch outcome is reconciled read-only, never attempts duplicate ref creation',async()=>{const {body,source}=await reportFixture(),pending=validateReport(body,[source]),stub=env.REPORT_OPERATIONS.getByName(body.operationId);await stub.receive(pending);await stub.transition(body.operationId,'received','delivering');await stub.transition(body.operationId,'delivering','pending_approval');await stub.transition(body.operationId,'pending_approval','creating_pr');await stub.transition(body.operationId,'creating_pr','provider_unknown');const github=fetchMock.get('https://api.github.com'),prefix='/repos/shicheng0810/question-bank-source';github.intercept({path:prefix+'/pulls?state=all&head=shicheng0810:codex/report-'+body.operationId,method:'GET'}).reply(200,[]);github.intercept({path:prefix+'/git/ref/heads/codex/report-'+body.operationId,method:'GET'}).reply(200,{object:{sha:'b'.repeat(40)}});github.intercept({path:prefix+'/contents/content/report-requests/'+body.operationId+'.json?ref='+'b'.repeat(40),method:'GET'}).reply(200,{content:btoa(JSON.stringify({format:'qb-native-report-request-v1',pending,baseCommit:'a'.repeat(40)}))});tg().intercept({path:'/botlocal-fake/answerCallbackQuery',method:'POST'}).reply(200,{ok:true});await webhook(callback(body.operationId));const row=await stub.get(body.operationId);expect(row.state).toBe('provider_unknown');expect(JSON.parse(row.result).reconciliation).toBe('branch_exists_pull_missing');});
it('existing PR with wrong source/fork or closed-unmerged is never recognized as queued success',async()=>{const {body,source}=await reportFixture(),pending=validateReport(body,[source]),repo={full_name:'shicheng0810/question-bank-source'},prefix='/repos/shicheng0810/question-bank-source';const valid={number:12,state:'open',base:{ref:'source',repo},head:{ref:'codex/report-'+body.operationId,repo,sha:'b'.repeat(40)}};for(const invalid of [{...valid,base:{ref:'main',repo}},{...valid,head:{...valid.head,repo:{full_name:'attacker/fork'}}},{...valid,state:'closed',merged_at:null}]){fetchMock.get('https://api.github.com').intercept({path:prefix+'/pulls?state=all&head=shicheng0810:codex/report-'+body.operationId,method:'GET'}).reply(200,[invalid]);await expect(reconcileNativeReportPR(env,pending)).rejects.toThrow(/REPORT_EXISTING_PR_IDENTITY_CONFLICT|REPORT_PR_CLOSED_UNMERGED/);}});
it('interrupted delivery inspection is read-only and retains actual state',async()=>{const {body,source}=await reportFixture(),stub=env.REPORT_OPERATIONS.getByName(body.operationId);await stub.receive(validateReport(body,[source]));await stub.transition(body.operationId,'received','delivering');const result=await inspectNativeReportOperation(env,body.operationId);expect(result.action).toBe('needs_delivery_review_no_automatic_resend');expect((await stub.get(body.operationId)).state).toBe('delivering');});
it('existing PR cannot reconcile a mismatched request payload or invalid request format',async()=>{
  const {body,source}=await reportFixture(),pending=validateReport(body,[source]),repo={full_name:'shicheng0810/question-bank-source'},prefix='/repos/shicheng0810/question-bank-source',sha='b'.repeat(40);
  for(const saved of [{format:'invalid',baseCommit:'a'.repeat(40),pending:publicCorrection(pending)},{format:'qb-native-report-request-v1',baseCommit:'a'.repeat(40),pending:{...publicCorrection(pending),corrected:{question:'different'}}}]){
    const gh=fetchMock.get('https://api.github.com');gh.intercept({path:prefix+'/pulls?state=all&head=shicheng0810:codex/report-'+body.operationId,method:'GET'}).reply(200,[{state:'open',base:{ref:'source',repo},head:{ref:'codex/report-'+body.operationId,repo,sha}}]);gh.intercept({path:prefix+'/contents/content/report-requests/'+body.operationId+'.json?ref='+sha,method:'GET'}).reply(200,{content:btoa(JSON.stringify(saved))});
    await expect(reconcileNativeReportPR(env,pending)).rejects.toThrow('REPORT_OPERATION_CONFLICT');
  }
});
